version: '3.9'

services:
  authenticationapi:
    image: ghcr.io/tanapoomjaisabay/authenticationapi:latest
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User=sa;Password=Your_password123;
      - TZ=Asia/Bangkok
    depends_on:
      - sqlserver
      
  customerapi:
    image: ghcr.io/tanapoomjaisabay/customerapi:latest
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=UAT
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MyDb;User=sa;Password=Your_password123;
      - TZ=Asia/Bangkok
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Passw0rd
      - ACCEPT_EULA=Y
      - TZ=Asia/Bangkok
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data: 
